# Initialize the wallpaper daemon
exec-once = awww-daemon

# Start waybar
exec-once = waybar

# Start auth agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Start hyprsunset
exec-once = hyprsunset

# Start notification daemon
exec-once = mako

# Launch signal at PC start in system tray
exec-once = signal-desktop