source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/autostart.conf

# HyprEmoji config
source = ~/.config/hypremoji/hypremoji.conf
# Make HyprEmoji display in the middle of the screen.
windowrule = center 1, match:title ^(HyprEmoji)$

# Allows Flatpaks to appear in Rofi.
env = XDG_DATA_DIRS,$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:~/.local/share/flatpak/exports/share