# System-wide dark mode
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
env = QT_QPA_PLATFORMTHEME,qt6ct
env = GTK_THEME,Adwaita-dark

# Cursor
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
# 2. Force GTK applications to use the new cursor theme and size
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
# 3. Explicitly initialize the cursor theme within Hyprland on startup
exec-once = hyprctl setcursor Bibata-Modern-Classic 24