# System-wide dark mode
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
env = QT_QPA_PLATFORMTHEME,qt6ct
env = GTK_THEME,Adwaita-dark

# Cursor
env = XCURSOR_THEME,GoogleDot-Black
env = XCURSOR_SIZE,24
# Force GTK applications to use the new cursor theme and size
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'GoogleDot-Black'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
# Start cursor with Hyprland
exec-once = hyprctl setcursor GoogleDot-Black 24